// =============================================================================
// PATIENT SERVICE
// =============================================================================
//
// PURPOSE:
// - Handle all patient-related API calls
// - CRUD operations (Create, Read, Update, Delete)
// - Patient search functionality
//
// BACKEND ENDPOINTS REQUIRED:
// - GET /api/patients - List all patients
// - POST /api/patients - Create new patient
// - GET /api/patients/:id - Get single patient
// - PUT /api/patients/:id - Update patient
// - DELETE /api/patients/:id - Delete patient
// - GET /api/patients/search?q=... - Search patients
//
// =============================================================================

import api from './authService'

// =============================================================================
// CREATE PATIENT
// =============================================================================
/**
 * Creates a new patient record
 * 
 * @param {Object} patientData - Patient information
 * @returns {Promise<Object>} - Created patient object
 * 
 * BACKEND ENDPOINT: POST /api/patients
 * 
 * REQUEST BODY EXAMPLE:
 * {
 *   "first_name": "Malik",
 *   "last_name": "Fernando",
 *   "age": 38,
 *   "gender": "Male",
 *   "date_of_birth": "1985-03-15",
 *   "nationality": "Sri Lankan",
 *   "national_id": "851234567V",
 *   "mobile_number": "+94771234567",
 *   "email": "malik@example.com",
 *   "preferred_language": "Sinhala",
 *   "blood_type": "O+",
 *   "chronics": "Diabetes Type 2",
 *   "allergies": "Penicillin",
 *   "drug_precautions": "Avoid NSAIDs"
 * }
 * 
 * EXPECTED RESPONSE:
 * {
 *   "id": "123",
 *   "mrn": "MRN001234",
 *   ...all patient data...
 *   "created_at": "2026-02-10T10:30:00Z"
 * }
 * 
 * MEDICAL NOTES:
 * - MRN (Medical Record Number) should be auto-generated by backend
 * - Date of birth is used to calculate age
 * - Chronics, allergies, drug_precautions are optional but important
 */
export const createPatient = async (patientData) => {
  const response = await api.post('/patients', patientData)
  return response.data
}

// =============================================================================
// GET PATIENTS LIST
// =============================================================================
/**
 * Fetches list of all patients with optional filters
 * 
 * @param {Object} params - Query parameters for filtering/pagination
 * @returns {Promise<Object>} - { results: Array, total: number, page: number }
 * 
 * BACKEND ENDPOINT: GET /api/patients
 * 
 * QUERY PARAMETERS (all optional):
 * - page: number (default: 1)
 * - limit: number (default: 20)
 * - gender: string (Male/Female/Other)
 * - age_min: number
 * - age_max: number
 * - nationality: string
 * 
 * EXAMPLE USAGE:
 * getPatients({ page: 1, limit: 20, gender: 'Male' })
 * 
 * EXPECTED RESPONSE:
 * {
 *   "results": [
 *     { id: "1", mrn: "MRN001234", first_name: "Malik", ... },
 *     { id: "2", mrn: "MRN005678", first_name: "Shiman", ... }
 *   ],
 *   "total": 248,
 *   "page": 1,
 *   "pages": 13
 * }
 */
export const getPatients = async (params = {}) => {
  const response = await api.get('/patients', { params })
  return response.data
}

// =============================================================================
// GET SINGLE PATIENT
// =============================================================================
/**
 * Fetches detailed information for a specific patient
 * 
 * @param {string} id - Patient ID or MRN
 * @returns {Promise<Object>} - Patient object
 * 
 * BACKEND ENDPOINT: GET /api/patients/:id
 * 
 * EXAMPLE: getPatientById('MRN001234')
 * 
 * EXPECTED RESPONSE:
 * {
 *   "id": "123",
 *   "mrn": "MRN001234",
 *   "first_name": "Malik",
 *   "last_name": "Fernando",
 *   ... all patient data ...
 *   "sessions": [
 *     { id: "1", date: "2026-01-15", complaint: "Headache" },
 *     { id: "2", date: "2026-02-01", complaint: "Follow-up" }
 *   ]
 * }
 */
export const getPatientById = async (id) => {
  const response = await api.get(`/patients/${id}`)
  return response.data
}

// =============================================================================
// UPDATE PATIENT
// =============================================================================
/**
 * Updates existing patient information
 * 
 * @param {string} id - Patient ID or MRN
 * @param {Object} patientData - Updated patient data
 * @returns {Promise<Object>} - Updated patient object
 * 
 * BACKEND ENDPOINT: PUT /api/patients/:id
 * 
 * REQUEST BODY: Same as createPatient, but all fields optional
 * 
 * EXAMPLE:
 * updatePatient('MRN001234', { 
 *   mobile_number: '+94771234567',
 *   allergies: 'Penicillin, Sulfa'
 * })
 */
export const updatePatient = async (id, patientData) => {
  const response = await api.put(`/patients/${id}`, patientData)
  return response.data
}

// =============================================================================
// DELETE PATIENT
// =============================================================================
/**
 * Deletes a patient record
 * 
 * @param {string} id - Patient ID or MRN
 * @returns {Promise<Object>} - Success message
 * 
 * BACKEND ENDPOINT: DELETE /api/patients/:id
 * 
 * SECURITY NOTE:
 * - Should require confirmation
 * - Consider soft-delete (mark as inactive) instead of hard delete
 * - Preserve medical records for legal compliance
 * 
 * EXPECTED RESPONSE:
 * {
 *   "message": "Patient deleted successfully"
 * }
 */
export const deletePatient = async (id) => {
  const response = await api.delete(`/patients/${id}`)
  return response.data
}

// =============================================================================
// SEARCH PATIENTS
// =============================================================================
/**
 * Searches patients by name, MRN, mobile, or NIC
 * 
 * @param {string} query - Search term
 * @returns {Promise<Array>} - Array of matching patients
 * 
 * BACKEND ENDPOINT: GET /api/patients/search?q=malik
 * 
 * BACKEND SHOULD SEARCH:
 * - First name
 * - Last name
 * - MRN
 * - Mobile number
 * - National ID
 * 
 * EXPECTED RESPONSE:
 * {
 *   "results": [
 *     { id: "1", mrn: "MRN001234", first_name: "Malik", ... }
 *   ],
 *   "total": 1
 * }
 */
export const searchPatients = async (query) => {
  const response = await api.get('/patients/search', { params: { q: query } })
  return response.data
}

// =============================================================================
// SEARCH BY COMPLAINT
// =============================================================================
/**
 * Finds patients by their past complaints/diagnoses
 * Useful for finding similar cases
 * 
 * @param {string} complaint - Complaint/diagnosis term
 * @returns {Promise<Array>} - Array of patients with matching complaints
 * 
 * BACKEND ENDPOINT: GET /api/patients/search/complaint?q=headache
 * 
 * USE CASE:
 * - Doctor wants to review all headache cases
 * - Find patients with similar conditions
 * - Research/study purposes
 * 
 * EXPECTED RESPONSE:
 * {
 *   "results": [
 *     { 
 *       patient: { id: "1", mrn: "MRN001234", ... },
 *       matching_sessions: [
 *         { id: "1", date: "2026-01-15", complaint: "Severe headache" }
 *       ]
 *     }
 *   ]
 * }
 */
export const searchByComplaint = async (complaint) => {
  const response = await api.get('/patients/search/complaint', { params: { q: complaint } })
  return response.data
}

// =============================================================================
// GET PATIENT BY MRN (Helper function)
// =============================================================================
/**
 * Convenience function to get patient specifically by MRN
 * Backend should handle both ID and MRN in the same endpoint
 * 
 * @param {string} mrn - Medical Record Number
 * @returns {Promise<Object>} - Patient object
 */
export const getPatientByMRN = async (mrn) => {
  return getPatientById(mrn)
}