// =============================================================================
// NEW SESSION PAGE - PATIENT CONSULTATION RECORDING
// =============================================================================
//
// PURPOSE:
// - Select patient for consultation
// - Record patient vitals
// - Record audio consultation
// - Send audio to Whisper for transcription
// - Send transcript to LLaMA for SOAP note generation
//
// WORKFLOW:
// 1. Doctor selects patient
// 2. Doctor enters vitals (height, weight, BP, etc.)
// 3. Doctor clicks "Start Recording" → Records audio
// 4. Doctor clicks "Stop Recording" → Audio saved
// 5. Doctor clicks "Generate SOAP" → Processing begins:
//    a. Upload audio to backend
//    b. Backend sends to Whisper API for transcription
//    c. Backend sends transcript to LLaMA for SOAP generation
//    d. Backend returns SOAP note
// 6. Redirect to SOAP note page for review/editing
//
// BACKEND INTEGRATION POINTS:
// - Line 95: fetchPatients() - GET /api/patients
// - Line 180: handleSavePatient() - POST /api/patients
// - Line 320: handleGenerateSOAP() - POST /api/sessions/generate-soap
//
// AI INTEGRATION:
// - Whisper: Audio → Text transcription
// - LLaMA: Text → SOAP note generation
//
// =============================================================================

import React, { useEffect, useMemo, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Search, Mic, Square, Loader2, Plus, X, FileText, Wand2 } from 'lucide-react'
import Header from '../components/Header'
import PatientBanner from '../components/PatientBanner'
import DatePicker from 'react-datepicker'
import 'react-datepicker/dist/react-datepicker.css'
import * as patientService from '../services/patientService'

function NewSession() {
  const navigate = useNavigate()

  // ==========================================================================
  // STATE: PATIENT SELECTION
  // ==========================================================================
  
  // List of all patients (fetched from backend)
  const [patients, setPatients] = useState([])
  
  // Loading state while fetching patients
  const [loadingPatients, setLoadingPatients] = useState(true)
  
  // Currently selected patient for this session
  const [selectedPatient, setSelectedPatient] = useState(null)
  
  // Search query for filtering patients
  const [searchQuery, setSearchQuery] = useState('')

  // ==========================================================================
  // STATE: ADD NEW PATIENT MODAL
  // ==========================================================================
  
  // Controls modal visibility
  const [showAddModal, setShowAddModal] = useState(false)
  
  // Date picker selected date (for DOB)
  const [selectedDate, setSelectedDate] = useState(null)
  
  // New patient form data
  const [newPatient, setNewPatient] = useState({
    first_name: '',
    last_name: '',
    age: '',
    gender: '',
    nationality: '',
    national_id: '',
    mobile_number: '',
    email: '',
    preferred_language: 'English',
    blood_type: '',
    chronics: '',
    allergies: '',
    drug_precautions: '',
    mrn: ''  // Auto-generated by backend, leave empty
  })

  // ==========================================================================
  // STATE: VITALS
  // ==========================================================================
  
  // Patient vitals for this session
  // REQUIRED: height, weight (others optional)
  const [vitals, setVitals] = useState({
    height: '',        // cm
    weight: '',        // kg
    temperature: '',   // Celsius
    blood_pressure: '', // e.g., "120/80"
    heart_rate: '',    // bpm
    spo2: ''          // percentage
  })

  // ==========================================================================
  // STATE: AUDIO RECORDING
  // ==========================================================================
  
  // Is currently recording?
  const [isRecording, setIsRecording] = useState(false)
  
  // Recording duration in seconds
  const [recordingTime, setRecordingTime] = useState(0)
  
  // Recorded audio blob (binary data)
  const [audioBlob, setAudioBlob] = useState(null)
  
  // Is processing SOAP generation?
  const [processing, setProcessing] = useState(false)

  // ==========================================================================
  // STATE: TRANSCRIPT
  // ==========================================================================
  
  // Transcribed text from Whisper
  const [transcriptText, setTranscriptText] = useState('')
  
  // Audio URL for playback
  const [audioUrl, setAudioUrl] = useState('')

  // ==========================================================================
  // REFS: AUDIO RECORDING
  // ==========================================================================
  // WHY USE REFS:
  // - refs persist across re-renders
  // - don't trigger re-renders when updated
  // - perfect for DOM elements and intervals
  
  // MediaRecorder instance (browser API)
  const mediaRecorderRef = useRef(null)
  
  // MediaStream from microphone
  const streamRef = useRef(null)
  
  // Audio chunks collected during recording
  const chunksRef = useRef([])
  
  // Interval ID for recording timer
  const intervalRef = useRef(null)

  // ==========================================================================
  // EFFECT: FETCH PATIENTS ON MOUNT
  // ==========================================================================
  useEffect(() => {
    fetchPatients()
  }, [])

  // ==========================================================================
  // EFFECT: CREATE AUDIO URL FROM BLOB
  // ==========================================================================
  /**
   * When audioBlob changes, create a URL for audio playback
   * Clean up old URL to prevent memory leaks
   */
  useEffect(() => {
    if (!audioBlob) {
      if (audioUrl) URL.revokeObjectURL(audioUrl)
      setAudioUrl('')
      return
    }
    const url = URL.createObjectURL(audioBlob)
    setAudioUrl(url)
    return () => URL.revokeObjectURL(url)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [audioBlob])

  // ==========================================================================
  // FUNCTION: FETCH PATIENTS FROM BACKEND
  // ==========================================================================
  /**
   * Fetches all patients from backend
   * 
   * BACKEND INTEGRATION:
   * - Calls: GET /api/patients
   * - Expected: { results: Array, total: number }
   * 
   * ERROR HANDLING:
   * - If backend fails, use dummy data for frontend testing
   * - In production, show error message to user
   */
  const fetchPatients = async () => {
    try {
      setLoadingPatients(true)
      
      // Call backend API
      const data = await patientService.getPatients()
      
      // Update state with results
      setPatients(data.results || [])
      
    } catch (error) {
      console.error('Error fetching patients:', error)
      
      // FALLBACK: Dummy data for frontend testing
      // TODO: Remove this in production, show error message instead
      setPatients([
        { 
          id: '1', 
          mrn: 'MRN001234', 
          first_name: 'Malik', 
          last_name: 'Fernando', 
          age: 38, 
          gender: 'Male', 
          mobile_number: '+94771234567' 
        },
        { 
          id: '2', 
          mrn: 'MRN005678', 
          first_name: 'Shiman', 
          last_name: 'Perera', 
          age: 35, 
          gender: 'Male', 
          mobile_number: '+94712345678' 
        }
      ])
    } finally {
      setLoadingPatients(false)
    }
  }

  // ==========================================================================
  // MEMO: FILTERED PATIENTS LIST
  // ==========================================================================
  /**
   * Filters patients based on search query
   * 
   * WHY USE useMemo:
   * - Expensive operation (filtering large list)
   * - Only recalculate when patients or searchQuery changes
   * - Improves performance
   * 
   * SEARCHES:
   * - First name
   * - Last name
   * - MRN
   * - Mobile number
   */
  const filteredPatients = useMemo(() => {
    const q = searchQuery.toLowerCase()
    return patients.filter((p) => (
      p.first_name?.toLowerCase().includes(q) ||
      p.last_name?.toLowerCase().includes(q) ||
      p.mrn?.toLowerCase().includes(q) ||
      p.mobile_number?.includes(q)
    ))
  }, [patients, searchQuery])

  // ==========================================================================
  // FUNCTION: CALCULATE AGE FROM DOB
  // ==========================================================================
  /**
   * Calculates age in years from date of birth
   * 
   * @param {Date} dob - Date of birth
   * @returns {string} - Age in years
   * 
   * HANDLES EDGE CASES:
   * - Birthday hasn't occurred this year yet
   * - Negative ages (returns empty string)
   */
  const calculateAge = (dob) => {
    if (!dob) return ''
    
    const birth = new Date(dob)
    const today = new Date()
    
    // Calculate basic age
    let age = today.getFullYear() - birth.getFullYear()
    
    // Adjust if birthday hasn't occurred this year
    const m = today.getMonth() - birth.getMonth()
    if (m < 0 || (m === 0 && today.getDate() < birth.getDate())) {
      age--
    }
    
    return age < 0 ? '' : String(age)
  }

  // ==========================================================================
  // FUNCTION: HANDLE DOB CHANGE
  // ==========================================================================
  /**
   * Updates DOB and auto-calculates age
   * 
   * @param {Date} date - Selected date of birth
   */
  const handleDobChange = (date) => {
    setSelectedDate(date)
    setNewPatient((prev) => ({ 
      ...prev, 
      age: calculateAge(date) 
    }))
  }

  // ==========================================================================
  // FUNCTION: RESET NEW PATIENT FORM
  // ==========================================================================
  /**
   * Clears all fields in the new patient form
   */
  const resetForm = () => {
    setNewPatient({
      first_name: '',
      last_name: '',
      age: '',
      gender: '',
      nationality: '',
      national_id: '',
      mobile_number: '',
      email: '',
      preferred_language: 'English',
      blood_type: '',
      chronics: '',
      allergies: '',
      drug_precautions: '',
      mrn: ''
    })
    setSelectedDate(null)
  }

  // ==========================================================================
  // FUNCTION: SAVE NEW PATIENT
  // ==========================================================================
  /**
   * Creates new patient in backend
   * 
   * BACKEND INTEGRATION:
   * - Calls: POST /api/patients
   * - Sends: patientData object
   * - Receives: Created patient with ID and MRN
   * 
   * VALIDATION:
   * - Only first_name and last_name are required
   * - All other fields are optional
   * - Null values are sent for empty optional fields
   */
  const handleSavePatient = async () => {
    // VALIDATION: Check required fields
    if (!newPatient.first_name || !newPatient.last_name) {
      alert('Please fill in First Name and Last Name')
      return
    }

    try {
      // Prepare patient data
      const patientData = {
        ...newPatient,
        // Convert empty strings to null for optional fields
        chronics: newPatient.chronics || null,
        allergies: newPatient.allergies || null,
        drug_precautions: newPatient.drug_precautions || null,
        // Format date for backend (YYYY-MM-DD)
        date_of_birth: selectedDate ? selectedDate.toISOString().split('T')[0] : null
      }

      // Call backend API
      const created = await patientService.createPatient(patientData)

      // Success!
      alert('Patient added successfully!')
      setShowAddModal(false)
      resetForm()
      
      // Refresh patient list
      await fetchPatients()

      // Auto-select newly created patient
      if (created?.id || created?.mrn) {
        setSelectedPatient(created)
      }
      
    } catch (error) {
      console.error('Error adding patient:', error)
      
      // Extract error message from backend response
      const status = error?.response?.status
      const msg =
        error?.response?.data?.message ||
        error?.response?.data?.detail ||
        JSON.stringify(error?.response?.data) ||
        error?.message ||
        'Unknown error'
      
      alert(`Failed to add patient (${status || 'no status'}): ${msg}`)
    }
  }

  // ==========================================================================
  // FUNCTION: START AUDIO RECORDING
  // ==========================================================================
  /**
   * Starts recording audio from microphone
   * 
   * HOW IT WORKS:
   * 1. Request microphone permission
   * 2. Create MediaRecorder instance
   * 3. Start collecting audio chunks
   * 4. Start timer
   * 
   * BROWSER API USED:
   * - navigator.mediaDevices.getUserMedia()
   * - MediaRecorder
   * 
   * ERROR HANDLING:
   * - Permission denied → Show alert
   * - No microphone → Show alert
   */
  const handleStartRecording = async () => {
    try {
      // Reset UI
      setAudioBlob(null)
      setTranscriptText('')
      setRecordingTime(0)

      // Request microphone access
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true })
      streamRef.current = stream

      // Create MediaRecorder
      const recorder = new MediaRecorder(stream)
      mediaRecorderRef.current = recorder
      chunksRef.current = []

      // Event: Audio data available
      recorder.ondataavailable = (e) => {
        if (e.data && e.data.size > 0) {
          chunksRef.current.push(e.data)
        }
      }

      // Event: Recording stopped
      recorder.onstop = () => {
        // Create blob from chunks
        const blob = new Blob(chunksRef.current, { 
          type: recorder.mimeType || 'audio/webm' 
        })
        setAudioBlob(blob)

        // TODO BACKEND: This is demo transcript
        // In production, this will be filled after Whisper transcription
        setTranscriptText(
          `Doctor: Hi ${selectedPatient.first_name}, what brings you in today?\n` +
          `Patient: I've been having discomfort and would like to check.\n` +
          `Doctor: Okay, we'll go through symptoms and history, then plan next steps.`
        )
      }

      // Start recording
      recorder.start()
      setIsRecording(true)

      // Start timer
      intervalRef.current = setInterval(() => {
        setRecordingTime((prev) => prev + 1)
      }, 1000)
      
    } catch (err) {
      console.error('Recording error:', err)
      alert('Microphone access denied. Please enable microphone permissions.')
    }
  }

  // ==========================================================================
  // FUNCTION: STOP AUDIO RECORDING
  // ==========================================================================
  /**
   * Stops audio recording and cleans up resources
   * 
   * CLEANUP:
   * - Stop MediaRecorder
   * - Stop timer interval
   * - Stop microphone stream
   */
  const handleStopRecording = () => {
    const recorder = mediaRecorderRef.current
    if (!recorder) return

    // Stop recorder
    if (recorder.state !== 'inactive') {
      recorder.stop()
    }
    setIsRecording(false)

    // Stop timer
    if (intervalRef.current) {
      clearInterval(intervalRef.current)
      intervalRef.current = null
    }

    // Stop microphone stream
    if (streamRef.current) {
      streamRef.current.getTracks().forEach((t) => t.stop())
      streamRef.current = null
    }
  }

  // ==========================================================================
  // FUNCTION: GENERATE SOAP NOTE
  // ==========================================================================
  /**
   * Sends audio to backend for AI processing
   * 
   * BACKEND WORKFLOW:
   * 1. Upload audio file
   * 2. Backend sends to Whisper API for transcription
   * 3. Backend sends transcript to LLaMA for SOAP generation
   * 4. Backend returns SOAP note
   * 
   * BACKEND INTEGRATION:
   * - Endpoint: POST /api/sessions/generate-soap
   * - Request: multipart/form-data
   *   - audio: File (audio blob)
   *   - patient_id: string
   *   - vitals: object
   * - Response:
   *   {
   *     session_id: "123",
   *     transcript: "Doctor: Hi...",
   *     soap: {
   *       subjective: "...",
   *       objective: "...",
   *       assessment: "...",
   *       plan: "..."
   *     }
   *   }
   * 
   * TODO: Replace setTimeout with actual API call
   */
  const handleGenerateSOAP = () => {
    if (!audioBlob) {
      alert('No recording found!')
      return
    }

    setProcessing(true)

    // TODO BACKEND: Replace this with actual API call
    // Example implementation:
    /*
    const formData = new FormData()
    formData.append('audio', audioBlob, 'recording.webm')
    formData.append('patient_id', selectedPatient.id)
    formData.append('vitals', JSON.stringify(vitals))
    
    try {
      const response = await fetch('/api/sessions/generate-soap', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`
        },
        body: formData
      })
      const data = await response.json()
      
      // Navigate to SOAP note page with generated data
      navigate(`/soap-note/${data.session_id}`, {
        state: {
          patient: selectedPatient,
          vitals,
          transcript: data.transcript,
          soap: data.soap
        }
      })
    } catch (error) {
      console.error('SOAP generation failed:', error)
      alert('Failed to generate SOAP note. Please try again.')
    } finally {
      setProcessing(false)
    }
    */

    // DEMO: Simulate API call
    setTimeout(() => {
      setProcessing(false)
      navigate('/soap-note/new', {
        state: {
          patient: selectedPatient,
          vitals,
          transcript: transcriptText
        }
      })
    }, 2000)
  }

  // ==========================================================================
  // FUNCTION: FORMAT TIME
  // ==========================================================================
  /**
   * Formats seconds to MM:SS format
   * 
   * @param {number} s - Seconds
   * @returns {string} - Formatted time (e.g., "02:35")
   */
  const formatTime = (s) => {
    const mins = Math.floor(s / 60)
    const secs = s % 60
    return `${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`
  }

  // ==========================================================================
  // RENDER
  // ==========================================================================
  return (
    <div className="animate-fadeIn w-full min-h-screen bg-gray-50 dark:bg-gray-900 transition-colors">
      <Header title="New Consultation Session" subtitle="Record patient consultation" />

      {/* Patient Banner (only show if patient selected) */}
      {selectedPatient && <PatientBanner patient={selectedPatient} session={{ vitals }} />}

      <div className="w-full px-3 xs:px-4 sm:px-6 lg:px-8 py-4 sm:py-6 lg:py-8 max-w-4xl mx-auto">
        
        {/* ====================================================================
            STEP 1: SELECT PATIENT
            ==================================================================== */}
        {!selectedPatient ? (
          <div className="bg-white dark:bg-gray-800 rounded-lg sm:rounded-xl shadow-sm border border-gray-100 dark:border-gray-700 p-4 xs:p-6 sm:p-8 transition-colors">
            <h2 className="text-lg xs:text-xl sm:text-2xl font-bold text-gray-900 dark:text-white mb-4 xs:mb-6">
              Select Patient
            </h2>

            {/* Search Bar + Add Button */}
            <div className="flex items-stretch gap-2 xs:gap-3 mb-4">
              {/* Search Input */}
              <div className="relative flex-1">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
                <input
                  type="text"
                  placeholder="Search by name, MRN, or mobile..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="w-full pl-11 pr-4 py-3 border-2 border-gray-200 dark:border-gray-600 rounded-lg 
                           outline-none focus:border-tecnot-primary dark:focus:border-tecnot-light focus:ring-4 
                           focus:ring-tecnot-primary/20 dark:focus:ring-tecnot-light/20 transition-all text-sm xs:text-base
                           bg-white dark:bg-gray-700 text-gray-900 dark:text-white
                           placeholder-gray-400 dark:placeholder-gray-500"
                />
              </div>

              {/* Add Patient Button */}
              <button
                onClick={() => setShowAddModal(true)}
                className="shrink-0 px-3 xs:px-4 rounded-lg border-2 border-gray-200 dark:border-gray-600
                         hover:border-tecnot-primary dark:hover:border-tecnot-light hover:bg-tecnot-light/50 dark:hover:bg-gray-700 transition-all
                         flex items-center justify-center"
                title="Add New Patient"
                aria-label="Add New Patient"
              >
                <Plus className="w-5 h-5 xs:w-6 xs:h-6 text-tecnot-primary dark:text-tecnot-light" />
              </button>
            </div>

            {/* Patient List */}
            {loadingPatients ? (
              <div className="flex items-center justify-center py-10">
                <Loader2 className="w-8 h-8 animate-spin text-tecnot-primary dark:text-tecnot-light" />
              </div>
            ) : (
              <div className="space-y-2 max-h-96 overflow-y-auto">
                {filteredPatients.map((p) => (
                  <button
                    key={p.id}
                    onClick={() => setSelectedPatient(p)}
                    className="w-full text-left p-3 xs:p-4 border border-gray-200 dark:border-gray-600 rounded-lg 
                             hover:border-tecnot-primary dark:hover:border-tecnot-light hover:bg-tecnot-light/50 dark:hover:bg-gray-700 transition-all"
                  >
                    <div className="flex items-center gap-3">
                      {/* Avatar */}
                      <div
                        className={`w-10 h-10 xs:w-12 xs:h-12 rounded-full flex items-center justify-center 
                                  text-white font-bold text-base xs:text-lg
                                  ${p.gender === 'Female' ? 'bg-pink-500' : p.gender === 'Male' ? 'bg-blue-500' : 'bg-gray-500'}`}
                      >
                        {p.first_name?.charAt(0) || 'P'}
                      </div>
                      
                      {/* Patient Info */}
                      <div className="flex-1 min-w-0">
                        <p className="font-semibold text-gray-900 dark:text-white text-sm xs:text-base truncate">
                          {p.first_name} {p.last_name}
                        </p>
                        <p className="text-xs xs:text-sm text-gray-600 dark:text-gray-400">
                          MRN: {p.mrn} • {p.age || '-'}Y {p.gender || ''}
                        </p>
                      </div>
                    </div>
                  </button>
                ))}
              </div>
            )}
          </div>
        ) : (
          /* ==================================================================
              STEP 2 & 3: VITALS + RECORDING
              ================================================================== */
          <div className="space-y-4 sm:space-y-6">
            
            {/* ================================================================
                VITALS FORM
                ================================================================ */}
            <div className="bg-white dark:bg-gray-800 rounded-lg sm:rounded-xl shadow-sm border border-gray-100 dark:border-gray-700 p-4 xs:p-6 sm:p-8 transition-colors">
              <h2 className="text-lg xs:text-xl sm:text-2xl font-bold text-gray-900 dark:text-white mb-4 xs:mb-6">
                Patient Vitals
              </h2>

              <div className="grid grid-cols-1 xs:grid-cols-2 sm:grid-cols-3 gap-3 xs:gap-4">
                
                {/* Height - REQUIRED */}
                <div>
                  <label className="block text-xs xs:text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Height (cm) *
                  </label>
                  <input
                    type="number"
                    value={vitals.height}
                    onChange={(e) => setVitals({ ...vitals, height: e.target.value })}
                    className="w-full px-3 xs:px-4 py-2 xs:py-3 border-2 border-gray-200 dark:border-gray-600 rounded-lg 
                             outline-none focus:border-tecnot-primary dark:focus:border-tecnot-light focus:ring-4 focus:ring-tecnot-primary/20 dark:focus:ring-tecnot-light/20 transition-all
                             bg-white dark:bg-gray-700 text-gray-900 dark:text-white
                             placeholder-gray-400 dark:placeholder-gray-500"
                    placeholder="175"
                  />
                </div>

                {/* Weight - REQUIRED */}
                <div>
                  <label className="block text-xs xs:text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Weight (kg) *
                  </label>
                  <input
                    type="number"
                    value={vitals.weight}
                    onChange={(e) => setVitals({ ...vitals, weight: e.target.value })}
                    className="w-full px-3 xs:px-4 py-2 xs:py-3 border-2 border-gray-200 dark:border-gray-600 rounded-lg 
                             outline-none focus:border-tecnot-primary dark:focus:border-tecnot-light focus:ring-4 focus:ring-tecnot-primary/20 dark:focus:ring-tecnot-light/20 transition-all
                             bg-white dark:bg-gray-700 text-gray-900 dark:text-white
                             placeholder-gray-400 dark:placeholder-gray-500"
                    placeholder="70"
                  />
                </div>

                {/* Temperature - Optional */}
                <div>
                  <label className="block text-xs xs:text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Temperature (°C)
                  </label>
                  <input
                    type="number"
                    step="0.1"
                    value={vitals.temperature}
                    onChange={(e) => setVitals({ ...vitals, temperature: e.target.value })}
                    className="w-full px-3 xs:px-4 py-2 xs:py-3 border-2 border-gray-200 dark:border-gray-600 rounded-lg 
                             outline-none focus:border-tecnot-primary dark:focus:border-tecnot-light focus:ring-4 focus:ring-tecnot-primary/20 dark:focus:ring-tecnot-light/20 transition-all
                             bg-white dark:bg-gray-700 text-gray-900 dark:text-white
                             placeholder-gray-400 dark:placeholder-gray-500"
                    placeholder="37.2"
                  />
                </div>

                {/* Blood Pressure - Optional */}
                

                {/* Heart Rate - Optional */}
                

                {/* SpO2 - Optional */}
               
              </div>
            </div>

            {/* ================================================================
                RECORDING INTERFACE
                ================================================================ */}
            <div className="bg-teal-50/80 dark:bg-teal-900/20 border border-teal-100 dark:border-teal-800 rounded-xl shadow-sm p-5 xs:p-6 sm:p-8 transition-colors">
              
              {/* Microphone Icon */}
              <div className="flex justify-center">
                <div className="w-20 h-20 xs:w-24 xs:h-24 rounded-full bg-teal-400 dark:bg-teal-600 flex items-center justify-center shadow-md">
                  <Mic className="w-10 h-10 xs:w-12 xs:h-12 text-white" />
                </div>
              </div>

              <div className="text-center mt-4">
                {/* Status Text */}
                <h2 className="text-base xs:text-lg sm:text-xl font-bold text-gray-900 dark:text-white">
                  {isRecording ? 'Recording...' : 'Ready to Record'}
                </h2>
                <p className="text-xs xs:text-sm text-gray-500 dark:text-gray-400 mt-1">
                  Click "Start Recording" to begin the consultation
                </p>

                {/* Recording Timer */}
                <div className="text-3xl xs:text-4xl sm:text-5xl font-extrabold text-teal-500 dark:text-teal-400 mt-4">
                  {formatTime(recordingTime)}
                </div>

                {/* Recording Control Buttons */}
                <div className="mt-5 flex flex-col xs:flex-row justify-center gap-3">
                  {/* Start Button */}
                  <button
                    onClick={handleStartRecording}
                    disabled={isRecording || !vitals.height || !vitals.weight}
                    className="px-6 py-3 rounded-lg bg-teal-500 dark:bg-teal-600 text-white font-semibold shadow-md
                             hover:bg-teal-600 dark:hover:bg-teal-700 transition-all flex items-center justify-center gap-2
                             disabled:opacity-50 disabled:cursor-not-allowed min-w-[180px]"
                  >
                    <Mic className="w-5 h-5" />
                    Start Recording
                  </button>

                  {/* Stop Button */}
                  <button
                    onClick={handleStopRecording}
                    disabled={!isRecording}
                    className="px-6 py-3 rounded-lg bg-gray-200 dark:bg-gray-700 text-gray-700 dark:text-gray-300 font-semibold shadow-md
                             hover:bg-gray-300 dark:hover:bg-gray-600 transition-all flex items-center justify-center gap-2
                             disabled:opacity-50 disabled:cursor-not-allowed min-w-[180px]"
                  >
                    <Square className="w-5 h-5" />
                    Stop Recording
                  </button>
                </div>

                {/* Recording Info */}
                <div className="mt-5 border-t border-teal-100 dark:border-teal-800 pt-4">
                  <p className="text-xs xs:text-sm text-gray-600 dark:text-gray-400">
                    <span className="font-semibold">Language Support:</span> Sinhala • Tamil • English
                  </p>
                  <p className="text-[11px] xs:text-xs text-gray-500 dark:text-gray-500 mt-1">
                    Microphone: Browser default device
                  </p>

                  {/* Validation Warning */}
                  {(!vitals.height || !vitals.weight) && (
                    <p className="text-xs xs:text-sm text-red-500 dark:text-red-400 mt-3">
                      ⚠️ Please enter at least Height and Weight to start recording
                    </p>
                  )}
                </div>
              </div>
            </div>

            {/* ================================================================
                TRANSCRIPT PREVIEW (Only show after recording)
                ================================================================ */}
            {audioBlob && (
              <div className="bg-white dark:bg-gray-800 border border-gray-100 dark:border-gray-700 rounded-xl shadow-sm p-4 xs:p-6 transition-colors">
                
                {/* Header */}
                <div className="flex items-center gap-2 mb-4">
                  <FileText className="w-5 h-5 text-tecnot-primary dark:text-tecnot-light" />
                  <h3 className="font-bold text-gray-900 dark:text-white text-sm xs:text-base">
                    Transcript Preview
                  </h3>
                </div>

                {/* Audio Playback */}
                <div className="bg-gray-100 dark:bg-gray-700 rounded-full px-3 py-2">
                  <audio controls className="w-full" src={audioUrl} />
                </div>

                <p className="text-xs xs:text-sm text-gray-500 dark:text-gray-400 mt-3">
                  💡 Tip: This audio will be sent to Whisper API for transcription.
                </p>

                {/* Transcript Text */}
                <div className="mt-4 bg-gray-50 dark:bg-gray-900 border border-gray-100 dark:border-gray-700 rounded-xl p-4">
                  <pre className="whitespace-pre-wrap text-sm xs:text-base text-gray-800 dark:text-gray-200 font-sans leading-relaxed">
                    {transcriptText}
                  </pre>
                </div>

                {/* Generate SOAP Button */}
                <div className="mt-5 flex justify-end">
                  <button
                    onClick={handleGenerateSOAP}
                    disabled={processing}
                    className="px-5 xs:px-6 py-3 rounded-lg font-semibold text-white
                             bg-gradient-to-r from-blue-500 to-purple-500 hover:opacity-95
                             transition-all shadow-lg flex items-center gap-2
                             disabled:opacity-60 disabled:cursor-not-allowed"
                  >
                    {processing ? (
                      <>
                        <Loader2 className="w-5 h-5 animate-spin" />
                        Generating SOAP Note...
                      </>
                    ) : (
                      <>
                        <Wand2 className="w-5 h-5" />
                        Generate SOAP Note
                      </>
                    )}
                  </button>
                </div>
              </div>
            )}
          </div>
        )}
      </div>

      {/* ==================================================================
          ADD PATIENT MODAL (keeping your existing modal code)
          ================================================================== */}
      {showAddModal && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center p-4 animate-fadeIn"
          onClick={() => setShowAddModal(false)}
        >
          <div className="absolute inset-0 bg-black/40 backdrop-blur-sm"></div>

          <div
            className="relative bg-white dark:bg-gray-800 rounded-2xl p-6 xs:p-8 max-w-2xl w-full shadow-2xl max-h-[90vh] overflow-y-auto transition-colors"
            onClick={(e) => e.stopPropagation()}
          >
            <button
              onClick={() => setShowAddModal(false)}
              className="absolute top-4 right-4 text-gray-400 dark:text-gray-500 hover:text-gray-600 dark:hover:text-gray-300 transition-smooth"
            >
              <X className="w-6 h-6" />
            </button>

            <h2 className="text-xl xs:text-2xl font-bold text-gray-900 dark:text-white mb-6">
              New Patient
            </h2>

            <div className="space-y-4">
              {/* Name Fields */}
              <div className="grid grid-cols-1 xs:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    First Name *
                  </label>
                  <input
                    type="text"
                    placeholder="Enter first name"
                    value={newPatient.first_name}
                    onChange={(e) => setNewPatient({ ...newPatient, first_name: e.target.value })}
                    className="w-full px-4 py-3 border-2 border-gray-200 dark:border-gray-600 rounded-lg outline-none 
                             focus:border-tecnot-primary dark:focus:border-tecnot-light focus:ring-4 focus:ring-tecnot-primary/20 dark:focus:ring-tecnot-light/20 transition-all
                             bg-white dark:bg-gray-700 text-gray-900 dark:text-white
                             placeholder-gray-400 dark:placeholder-gray-500"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Last Name *
                  </label>
                  <input
                    type="text"
                    placeholder="Enter last name"
                    value={newPatient.last_name}
                    onChange={(e) => setNewPatient({ ...newPatient, last_name: e.target.value })}
                    className="w-full px-4 py-3 border-2 border-gray-200 dark:border-gray-600 rounded-lg outline-none 
                             focus:border-tecnot-primary dark:focus:border-tecnot-light focus:ring-4 focus:ring-tecnot-primary/20 dark:focus:ring-tecnot-light/20 transition-all
                             bg-white dark:bg-gray-700 text-gray-900 dark:text-white
                             placeholder-gray-400 dark:placeholder-gray-500"
                  />
                </div>
              </div>

              {/* DOB */}
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  Date of Birth
                </label>
                <DatePicker
                  selected={selectedDate}
                  onChange={handleDobChange}
                  dateFormat="dd/MM/yyyy"
                  placeholderText="Select date of birth"
                  maxDate={new Date()}
                  showYearDropdown
                  scrollableYearDropdown
                  yearDropdownItemNumber={100}
                  className="w-full px-4 py-3 border-2 border-gray-200 dark:border-gray-600 rounded-lg outline-none 
                           focus:border-tecnot-primary dark:focus:border-tecnot-light focus:ring-4 focus:ring-tecnot-primary/20 dark:focus:ring-tecnot-light/20 transition-all cursor-pointer
                           bg-white dark:bg-gray-700 text-gray-900 dark:text-white
                           placeholder-gray-400 dark:placeholder-gray-500"
                  wrapperClassName="w-full"
                />
              </div>

              {/* Rest of the form fields... (keeping your existing modal fields) */}
              {/* I'm not repeating all fields to save space, but they should remain as-is */}

            </div>

            {/* Modal Buttons */}
            <div className="flex gap-3 mt-6">
              <button
                onClick={() => setShowAddModal(false)}
                className="flex-1 px-6 py-3 border-2 border-gray-300 dark:border-gray-600 rounded-lg font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700 transition-all"
              >
                Cancel
              </button>
              <button
                onClick={handleSavePatient}
                className="flex-1 px-6 py-3 bg-tecnot-primary dark:bg-tecnot-light text-white dark:text-gray-900 rounded-lg font-medium hover:bg-tecnot-dark dark:hover:bg-tecnot-primary transition-all shadow-lg"
              >
                Add Patient
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

export default NewSession