import React, { useState } from 'react'
import { X } from 'lucide-react'
import DatePicker from 'react-datepicker'
import 'react-datepicker/dist/react-datepicker.css'
import * as patientService from '../services/patientService'

function AddPatientModal({ onClose, onSuccess }) {
    // Date picker for DOB
    const [selectedDate, setSelectedDate] = useState(null)
  
    // New patient form data
    const [newPatient, setNewPatient] = useState({
        first_name: '',
        last_name: '',
        age: '',
        gender: '',
        nationality: '',
        national_id: '',
        mobile_number: '',
        email: '',
        preferred_language: 'English',
        blood_type: '',
        chronics: '',
        allergies: '',
        drug_precautions: '',
        mrn: '' // Auto-generated by backend
    })

    // ==========================================================================
    // FUNCTION: CALCULATE AGE FROM DOB
    // ==========================================================================
    /**
     * Calculates age in years from date of birth
     * 
     * @param {Date} dob - Date of birth
     * @returns {string} - Age in years or empty string
     * 
     * HANDLES:
     * - Birthdays that haven't occurred this year yet
     * - Invalid/negative ages
     */
    const calculateAge = (dob) => {
        if (!dob) return ''
        
        const birth = new Date(dob)
        const today = new Date()
        let age = today.getFullYear() - birth.getFullYear()
        const m = today.getMonth() - birth.getMonth()
        
        // Adjust if birthday hasn't occurred this year
        if (m < 0 || (m === 0 && today.getDate() < birth.getDate())) {
        age--
        }
        
        return age < 0 ? '' : String(age)
    }

    // ==========================================================================
    // FUNCTION: HANDLE DOB CHANGE
    // ==========================================================================
    /**
     * Updates DOB and automatically calculates age
     */
    const handleDobChange = (date) => {
        setSelectedDate(date)
        const computedAge = calculateAge(date)
        setNewPatient(prev => ({ ...prev, age: computedAge }))
    }

    // ==========================================================================
    // FUNCTION: SAVE NEW PATIENT
    // ==========================================================================
    /**
     * Creates new patient in backend
     * 
     * BACKEND INTEGRATION:
     * - Endpoint: POST /api/patients
     * - Request body: patientData object
     * - Expected response: Created patient with id and mrn
     * 
     * VALIDATION:
     * - Only first_name and last_name are required
     * - All other fields are optional
     */
    const handleSavePatient = async () => {
        // Validate required fields
        if (!newPatient.first_name || !newPatient.last_name) {
        alert('Please fill in patient name')
        return
    }
    try{
      // Prepare patient data
      const patientData = {
        ...newPatient,
        // Format date for backend (YYYY-MM-DD)
        date_of_birth: selectedDate ? selectedDate.toISOString().split('T')[0] : null
      }
      
      // Call backend API
      const createdPatient = await patientService.createPatient(patientData)
      
      // Success!
      alert('Patient added successfully!')
      resetForm()
      onSuccess(createdPatient)
      
    } catch (error) {
      console.error('Error adding patient:', error)
      alert('Failed to add patient. Please try again.')
    }
    }

    // ==========================================================================
    // FUNCTION: RESET FORM
    // ==========================================================================
    /**
     * Clears all form fields and resets modal state
     */
    const resetForm = () => {
        setNewPatient({
        first_name: '',
        last_name: '',
        age: '',
        gender: '',
        nationality: '',
        national_id: '',
        mobile_number: '',
        email: '',
        preferred_language: 'English',
        blood_type: '',
        chronics: '',
        allergies: '',
        drug_precautions: '',
        mrn: ''
        })
        setSelectedDate(null)
    }

    /* ====================================================================
                                    ADD PATIENT MODAL
    ==================================================================== */
    return (
        <div
            className="fixed inset-0 z-50 flex items-center justify-center p-4 animate-fadeIn"
            onClick={onClose}
        >
            {/* Backdrop */}
            <div className="absolute inset-0 bg-black/40 backdrop-blur-sm"></div>

            {/* Modal */}
            <div
            className="relative bg-white dark:bg-gray-800 rounded-2xl p-6 xs:p-8 max-w-2xl w-full 
                        shadow-2xl max-h-[90vh] overflow-y-auto transition-colors"
            onClick={(e) => e.stopPropagation()}
            >
            {/* Close Button */}
            <button
                onClick={onClose}
                className="absolute top-4 right-4 text-gray-400 dark:text-gray-500 hover:text-gray-600 dark:hover:text-gray-300 transition-smooth"
            >
                <X className="w-6 h-6" />
            </button>

            <h2 className="text-xl xs:text-2xl font-bold text-gray-900 dark:text-white mb-6">
                New Patient
            </h2>

            <div className="space-y-4">
                
                {/* ============================================================
                    NAME FIELDS
                    ============================================================ */}
                <div className="grid grid-cols-1 xs:grid-cols-2 gap-4">
                {/* First Name - REQUIRED */}
                <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    First Name *
                    </label>
                    <input
                    type="text"
                    placeholder="Enter first name"
                    value={newPatient.first_name}
                    onChange={(e) => setNewPatient({ ...newPatient, first_name: e.target.value })}
                    className="w-full px-4 py-3 border-2 border-gray-200 dark:border-gray-600 rounded-lg outline-none 
                                focus:border-tecnot-primary dark:focus:border-tecnot-light focus:ring-4 focus:ring-tecnot-primary/20 dark:focus:ring-tecnot-light/20
                                transition-all text-sm xs:text-base
                                bg-white dark:bg-gray-700 text-gray-900 dark:text-white
                                placeholder-gray-400 dark:placeholder-gray-500"
                    />
                </div>
                
                {/* Last Name - REQUIRED */}
                <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Last Name *
                    </label>
                    <input
                    type="text"
                    placeholder="Enter last name"
                    value={newPatient.last_name}
                    onChange={(e) => setNewPatient({ ...newPatient, last_name: e.target.value })}
                    className="w-full px-4 py-3 border-2 border-gray-200 dark:border-gray-600 rounded-lg outline-none 
                                focus:border-tecnot-primary dark:focus:border-tecnot-light focus:ring-4 focus:ring-tecnot-primary/20 dark:focus:ring-tecnot-light/20
                                transition-all text-sm xs:text-base
                                bg-white dark:bg-gray-700 text-gray-900 dark:text-white
                                placeholder-gray-400 dark:placeholder-gray-500"
                    />
                </div>
                </div>

                {/* ============================================================
                    DATE OF BIRTH
                    ============================================================ */}
                <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Date of Birth
                </label>
                <DatePicker
                    selected={selectedDate}
                    onChange={handleDobChange}
                    dateFormat="dd/MM/yyyy"
                    placeholderText="Select date of birth"
                    maxDate={new Date()}
                    showYearDropdown
                    scrollableYearDropdown
                    yearDropdownItemNumber={100}
                    className="w-full px-4 py-3 border-2 border-gray-200 dark:border-gray-600 rounded-lg outline-none 
                            focus:border-tecnot-primary dark:focus:border-tecnot-light focus:ring-4 focus:ring-tecnot-primary/20 dark:focus:ring-tecnot-light/20
                            transition-all cursor-pointer text-sm xs:text-base
                            bg-white dark:bg-gray-700 text-gray-900 dark:text-white
                            placeholder-gray-400 dark:placeholder-gray-500"
                    wrapperClassName="w-full"
                />
                </div>

                {/* ============================================================
                    AGE & GENDER
                    ============================================================ */}
                <div className="grid grid-cols-1 xs:grid-cols-2 gap-4">
                {/* Age - Auto-calculated */}
                <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Age
                    </label>
                    <input
                    type="number"
                    placeholder="Auto-calculated from DOB"
                    value={newPatient.age}
                    onChange={(e) => setNewPatient({ ...newPatient, age: e.target.value })}
                    className="w-full px-4 py-3 border-2 border-gray-200 dark:border-gray-600 rounded-lg outline-none 
                                focus:border-tecnot-primary dark:focus:border-tecnot-light focus:ring-4 focus:ring-tecnot-primary/20 dark:focus:ring-tecnot-light/20
                                transition-all text-sm xs:text-base
                                bg-white dark:bg-gray-700 text-gray-900 dark:text-white
                                placeholder-gray-400 dark:placeholder-gray-500"
                    />
                </div>
                
                {/* Gender */}
                <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Gender
                    </label>
                    <select
                    value={newPatient.gender}
                    onChange={(e) => setNewPatient({ ...newPatient, gender: e.target.value })}
                    className="w-full px-4 py-3 border-2 border-gray-200 dark:border-gray-600 rounded-lg outline-none 
                                focus:border-tecnot-primary dark:focus:border-tecnot-light focus:ring-4 focus:ring-tecnot-primary/20 dark:focus:ring-tecnot-light/20
                                transition-all bg-white dark:bg-gray-700 cursor-pointer text-sm xs:text-base
                                text-gray-900 dark:text-white"
                    >
                    <option value="">Select Gender</option>
                    <option value="Male">Male</option>
                    <option value="Female">Female</option>
                    <option value="Other">Other</option>
                    </select>
                </div>
                </div>

                {/* ============================================================
                    NATIONALITY & NATIONAL ID
                    ============================================================ */}
                <div className="grid grid-cols-1 xs:grid-cols-2 gap-4">
                <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Nationality
                    </label>
                    <input
                    type="text"
                    placeholder="Enter nationality"
                    value={newPatient.nationality}
                    onChange={(e) => setNewPatient({ ...newPatient, nationality: e.target.value })}
                    className="w-full px-4 py-3 border-2 border-gray-200 dark:border-gray-600 rounded-lg outline-none 
                                focus:border-tecnot-primary dark:focus:border-tecnot-light focus:ring-4 focus:ring-tecnot-primary/20 dark:focus:ring-tecnot-light/20
                                transition-all text-sm xs:text-base
                                bg-white dark:bg-gray-700 text-gray-900 dark:text-white
                                placeholder-gray-400 dark:placeholder-gray-500"
                    />
                </div>
                <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    National ID
                    </label>
                    <input
                    type="text"
                    placeholder="e.g., 851234567V"
                    value={newPatient.national_id}
                    onChange={(e) => setNewPatient({ ...newPatient, national_id: e.target.value })}
                    className="w-full px-4 py-3 border-2 border-gray-200 dark:border-gray-600 rounded-lg outline-none 
                                focus:border-tecnot-primary dark:focus:border-tecnot-light focus:ring-4 focus:ring-tecnot-primary/20 dark:focus:ring-tecnot-light/20
                                transition-all text-sm xs:text-base
                                bg-white dark:bg-gray-700 text-gray-900 dark:text-white
                                placeholder-gray-400 dark:placeholder-gray-500"
                    />
                </div>
                </div>

                {/* ============================================================
                    MOBILE & EMAIL
                    ============================================================ */}
                <div className="grid grid-cols-1 xs:grid-cols-2 gap-4">
                <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Mobile Number
                    </label>
                    <input
                    type="tel"
                    placeholder="+94 77 123 4567"
                    value={newPatient.mobile_number}
                    onChange={(e) => setNewPatient({ ...newPatient, mobile_number: e.target.value })}
                    className="w-full px-4 py-3 border-2 border-gray-200 dark:border-gray-600 rounded-lg outline-none 
                                focus:border-tecnot-primary dark:focus:border-tecnot-light focus:ring-4 focus:ring-tecnot-primary/20 dark:focus:ring-tecnot-light/20
                                transition-all text-sm xs:text-base
                                bg-white dark:bg-gray-700 text-gray-900 dark:text-white
                                placeholder-gray-400 dark:placeholder-gray-500"
                    />
                </div>
                <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Email
                    </label>
                    <input
                    type="email"
                    placeholder="patient@example.com"
                    value={newPatient.email}
                    onChange={(e) => setNewPatient({ ...newPatient, email: e.target.value })}
                    className="w-full px-4 py-3 border-2 border-gray-200 dark:border-gray-600 rounded-lg outline-none 
                                focus:border-tecnot-primary dark:focus:border-tecnot-light focus:ring-4 focus:ring-tecnot-primary/20 dark:focus:ring-tecnot-light/20
                                transition-all text-sm xs:text-base
                                bg-white dark:bg-gray-700 text-gray-900 dark:text-white
                                placeholder-gray-400 dark:placeholder-gray-500"
                    />
                </div>
                </div>

                {/* ============================================================
                    LANGUAGE & BLOOD TYPE
                    ============================================================ */}
                <div className="grid grid-cols-1 xs:grid-cols-2 gap-4">
                <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Preferred Language
                    </label>
                    <select
                    value={newPatient.preferred_language}
                    onChange={(e) => setNewPatient({ ...newPatient, preferred_language: e.target.value })}
                    className="w-full px-4 py-3 border-2 border-gray-200 dark:border-gray-600 rounded-lg outline-none 
                                focus:border-tecnot-primary dark:focus:border-tecnot-light focus:ring-4 focus:ring-tecnot-primary/20 dark:focus:ring-tecnot-light/20
                                transition-all bg-white dark:bg-gray-700 cursor-pointer text-sm xs:text-base
                                text-gray-900 dark:text-white"
                    >
                    <option value="English">English</option>
                    <option value="Sinhala">Sinhala</option>
                    <option value="Tamil">Tamil</option>
                    </select>
                </div>
                <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Blood Type
                    </label>
                    <select
                    value={newPatient.blood_type}
                    onChange={(e) => setNewPatient({ ...newPatient, blood_type: e.target.value })}
                    className="w-full px-4 py-3 border-2 border-gray-200 dark:border-gray-600 rounded-lg outline-none 
                                focus:border-tecnot-primary dark:focus:border-tecnot-light focus:ring-4 focus:ring-tecnot-primary/20 dark:focus:ring-tecnot-light/20
                                transition-all bg-white dark:bg-gray-700 cursor-pointer text-sm xs:text-base
                                text-gray-900 dark:text-white"
                    >
                    <option value="">Select Blood Type</option>
                    <option value="A+">A+</option>
                    <option value="A-">A-</option>
                    <option value="B+">B+</option>
                    <option value="B-">B-</option>
                    <option value="AB+">AB+</option>
                    <option value="AB-">AB-</option>
                    <option value="O+">O+</option>
                    <option value="O-">O-</option>
                    </select>
                </div>
                </div>

                {/* ============================================================
                    MEDICAL INFORMATION (OPTIONAL)
                    ============================================================ */}
                <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Chronic Conditions
                </label>
                <input
                    type="text"
                    placeholder="e.g., Diabetes Type 2, Hypertension"
                    value={newPatient.chronics}
                    onChange={(e) => setNewPatient({ ...newPatient, chronics: e.target.value })}
                    className="w-full px-4 py-3 border-2 border-gray-200 dark:border-gray-600 rounded-lg outline-none 
                            focus:border-tecnot-primary dark:focus:border-tecnot-light focus:ring-4 focus:ring-tecnot-primary/20 dark:focus:ring-tecnot-light/20
                            transition-all text-sm xs:text-base
                            bg-white dark:bg-gray-700 text-gray-900 dark:text-white
                            placeholder-gray-400 dark:placeholder-gray-500"
                />
                </div>

                <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Allergies
                </label>
                <input
                    type="text"
                    placeholder="e.g., Penicillin, Peanuts"
                    value={newPatient.allergies}
                    onChange={(e) => setNewPatient({ ...newPatient, allergies: e.target.value })}
                    className="w-full px-4 py-3 border-2 border-gray-200 dark:border-gray-600 rounded-lg outline-none 
                            focus:border-tecnot-primary dark:focus:border-tecnot-light focus:ring-4 focus:ring-tecnot-primary/20 dark:focus:ring-tecnot-light/20
                            transition-all text-sm xs:text-base
                            bg-white dark:bg-gray-700 text-gray-900 dark:text-white
                            placeholder-gray-400 dark:placeholder-gray-500"
                />
                </div>

                <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Drug Precautions
                </label>
                <input
                    type="text"
                    placeholder="e.g., Avoid NSAIDs"
                    value={newPatient.drug_precautions}
                    onChange={(e) => setNewPatient({ ...newPatient, drug_precautions: e.target.value })}
                    className="w-full px-4 py-3 border-2 border-gray-200 dark:border-gray-600 rounded-lg outline-none 
                            focus:border-tecnot-primary dark:focus:border-tecnot-light focus:ring-4 focus:ring-tecnot-primary/20 dark:focus:ring-tecnot-light/20
                            transition-all text-sm xs:text-base
                            bg-white dark:bg-gray-700 text-gray-900 dark:text-white
                            placeholder-gray-400 dark:placeholder-gray-500"
                />
                </div>

                <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Patient MRN
                </label>
                <input
                    type="text"
                    placeholder="Auto-generated (leave blank)"
                    value={newPatient.mrn}
                    onChange={(e) => setNewPatient({ ...newPatient, mrn: e.target.value })}
                    className="w-full px-4 py-3 border-2 border-gray-200 dark:border-gray-600 rounded-lg outline-none 
                            focus:border-tecnot-primary dark:focus:border-tecnot-light focus:ring-4 focus:ring-tecnot-primary/20 dark:focus:ring-tecnot-light/20
                            transition-all text-sm xs:text-base
                            bg-white dark:bg-gray-700 text-gray-900 dark:text-white
                            placeholder-gray-400 dark:placeholder-gray-500"
                />
                </div>
            </div>

            {/* Modal Action Buttons */}
            <div className="flex gap-3 mt-6">
                <button
                onClick={onClose}
                className="flex-1 px-6 py-3 border-2 border-gray-300 dark:border-gray-600 rounded-lg font-medium 
                            text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700 transition-smooth text-sm xs:text-base"
                >
                Cancel
                </button>
                <button
                onClick={handleSavePatient}
                className="flex-1 px-6 py-3 bg-tecnot-primary dark:bg-tecnot-light text-white dark:text-gray-900 rounded-lg font-medium 
                            hover:bg-tecnot-dark dark:hover:bg-tecnot-primary transition-smooth shadow-lg hover:shadow-xl text-sm xs:text-base"
                >
                Add Patient
                </button>
            </div>
            </div>
        </div>
    )

}

export default AddPatientModal